project_id = "ifnxriqbrvheqbtbdimc"

[functions.session-guest]
verify_jwt = false

[functions.parse-resume]
verify_jwt = false

[functions.profile]
verify_jwt = false

[functions.skills-update-levels]
verify_jwt = false
